// backend/src/utils/emailValidator.js

/**
 * Comprehensive list of disposable/temporary email domains
 * These are commonly used for spam, abuse, or temporary registrations
 */
const DISPOSABLE_EMAIL_DOMAINS = [
    // Popular disposable email services
    "10minutemail.com",
    "10minutemail.net",
    "guerrillamail.com",
    "guerrillamail.net",
    "guerrillamail.org",
    "tempmail.com",
    "temp-mail.org",
    "throwaway.email",
    "mailinator.com",
    "mailinator2.com",
    "fakeinbox.com",
    "trashmail.com",
    "getnada.com",
    "maildrop.cc",
    "sharklasers.com",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "cool.fr.nf",
    "jetable.fr.nf",
    "nospam.ze.tc",
    "nomail.xl.cx",
    "mega.zik.dj",
    "speed.1s.fr",
    "courriel.fr.nf",
    "moncourrier.fr.nf",
    "monmail.fr.nf",
    "hide.biz.st",
    "mymail.infos.st",

    // Additional disposable services
    "dispostable.com",
    "mintemail.com",
    "emailondeck.com",
    "spamgourmet.com",
    "mailcatch.com",
    "mohmal.com",
    "anonymbox.com",
    "burnermail.io",
    "emailtemporanea.com",
    "emailtemporanea.net",
    "emailtemporar.ro",
    "emailtemporario.com.br",
    "emailna.co",
    "emailsensei.com",
    "emailthe.net",
    "emailtmp.com",
    "emailure.net",
    "emailxfer.com",
    "emeil.in",
    "emeil.ir",
    "emz.net",
    "evopo.com",
    "explodemail.com",
    "express.net.ua",
    "eyepaste.com",
    "fakemailgenerator.com",
    "fastacura.com",
    "fastchevy.com",
    "fastchrysler.com",
    "fastkawasaki.com",
    "fastmazda.com",
    "fastmitsubishi.com",
    "fastnissan.com",
    "fastsubaru.com",
    "fastsuzuki.com",
    "fasttoyota.com",
    "fastyamaha.com",
    "filzmail.com",
    "fivemail.de",
    "fleckens.hu",
    "frapmail.com",
    "freemail.ms",
    "freundin.ru",
    "garliclife.com",
    "gehensiemirnichtaufdensack.de",
    "get1mail.com",
    "getairmail.com",
    "getmails.eu",
    "getonemail.com",
    "gishpuppy.com",
    "gmial.com",
    "goemailgo.com",
    "gotmail.com",
    "gotmail.net",
    "gotmail.org",
    "gowikibooks.com",
    "gowikicampus.com",
    "gowikicars.com",
    "gowikifilms.com",
    "gowikigames.com",
    "gowikimusic.com",
    "gowikinetwork.com",
    "gowikitravel.com",
    "gowikitv.com",
    "great-host.in",
    "greensloth.com",
    "grr.la",
    "gsrv.co.uk",
    "guerillamail.biz",
    "guerillamail.de",
    "h.mintemail.com",
    "h8s.org",
    "haltospam.com",
    "hatespam.org",
    "hidemail.de",
    "hidzz.com",
    "hotpop.com",
    "ieatspam.eu",
    "ieatspam.info",
    "ihateyoualot.info",
    "iheartspam.org",
    "imails.info",
    "inboxclean.com",
    "inboxclean.org",
    "incognitomail.com",
    "incognitomail.net",
    "incognitomail.org",
    "insorg-mail.info",
    "instant-mail.de",
    "ip6.li",
    "irish2me.com",
    "iwi.net",
    "jetable.com",
    "jetable.net",
    "jetable.org",
    "jnxjn.com",
    "jourrapide.com",
    "jsrsolutions.com",
    "kasmail.com",
    "kaspop.com",
    "keepmymail.com",
    "killmail.com",
    "killmail.net",
    "kir.ch.tc",
    "klassmaster.com",
    "klassmaster.net",
    "klzlk.com",
    "koszmail.pl",
    "kurzepost.de",
    "lawlita.com",
    "letthemeatspam.com",
    "lhsdv.com",
    "lifebyfood.com",
    "link2mail.net",
    "litedrop.com",
    "lol.ovpn.to",
    "lolfreak.net",
    "lookugly.com",
    "lopl.co.cc",
    "lortemail.dk",
    "lr78.com",
    "lroid.com",
    "lukop.dk",
    "m4ilweb.info",
    "maboard.com",
    "mail-temporaire.fr",
    "mail.by",
    "mail.mezimages.net",
    "mail2rss.org",
    "mail333.com",
    "mail4trash.com",
    "mailbidon.com",
    "mailblocks.com",
    "mailbucket.org",
    "mailcat.biz",
    "mailcatch.com",
    "mailde.de",
    "mailde.info",
    "maildx.com",
    "maileater.com",
    "mailed.ro",
    "mailexpire.com",
    "mailfa.tk",
    "mailforspam.com",
    "mailfree.ga",
    "mailfree.gq",
    "mailfree.ml",
    "mailfreeonline.com",
    "mailfs.com",
    "mailguard.me",
    "mailimate.com",
    "mailin8r.com",
    "mailinater.com",
    "mailinator.gq",
    "mailinator.org",
    "mailinator.us",
    "mailincubator.com",
    "mailismagic.com",
    "mailme.gq",
    "mailme.ir",
    "mailme.lv",
    "mailme24.com",
    "mailmetrash.com",
    "mailmoat.com",
    "mailms.com",
    "mailnator.com",
    "mailnesia.com",
    "mailnull.com",
    "mailorg.org",
    "mailpick.biz",
    "mailproxsy.com",
    "mailquack.com",
    "mailrock.biz",
    "mailscrap.com",
    "mailseal.de",
    "mailshell.com",
    "mailsiphon.com",
    "mailslite.com",
    "mailtemp.info",
    "mailtome.de",
    "mailtothis.com",
    "mailtrash.net",
    "mailtv.net",
    "mailtv.tv",
    "mailzilla.com",
    "mailzilla.org",
    "makemetheking.com",
    "manybrain.com",
    "mbx.cc",
    "mega.zik.dj",
    "meinspamschutz.de",
    "meltmail.com",
    "messagebeamer.de",
    "mezimages.net",
    "ministry-of-silly-walks.de",
    "mintemail.com",
    "misterpinball.de",
    "moncourrier.fr.nf",
    "monemail.fr.nf",
    "monmail.fr.nf",
    "monumentmail.com",
    "mt2009.com",
    "mt2014.com",
    "mycard.net.ua",
    "mycleaninbox.net",
    "mymail-in.net",
    "mypacks.net",
    "mypartyclip.de",
    "myphantomemail.com",
    "mysamp.de",
    "mytempemail.com",
    "mytempmail.com",
    "mytrashmail.com",
    "nabuma.com",
    "neomailbox.com",
    "nepwk.com",
    "nervmich.net",
    "nervtmich.net",
    "netmails.com",
    "netmails.net",
    "netzidiot.de",
    "neverbox.com",
    "nice-4u.com",
    "nincsmail.hu",
    "nnh.com",
    "no-spam.ws",
    "noblepioneer.com",
    "nomail.pw",
    "nomail.xl.cx",
    "nomail2me.com",
    "nomorespamemails.com",
    "nospam.ze.tc",
    "nospam4.us",
    "nospamfor.us",
    "nospammail.net",
    "notmailinator.com",
    "nowhere.org",
    "nowmymail.com",
    "nurfuerspam.de",
    "nus.edu.sg",
    "objectmail.com",
    "obobbo.com",
    "odnorazovoe.ru",
    "oneoffemail.com",
    "onewaymail.com",
    "online.ms",
    "opayq.com",
    "ordinaryamerican.net",
    "otherinbox.com",
    "ovpn.to",
    "owlpic.com",
    "pancakemail.com",
    "paplease.com",
    "pcusers.otherinbox.com",
    "pepbot.com",
    "pimpedupmyspace.com",
    "pjjkp.com",
    "plexolan.de",
    "poczta.onet.pl",
    "politikerclub.de",
    "poofy.org",
    "pookmail.com",
    "privacy.net",
    "privatdemail.net",
    "proxymail.eu",
    "prtnx.com",
    "putthisinyourspamdatabase.com",
    "qq.com",
    "quickinbox.com",
    "quickmail.nl",
    "rcpt.at",
    "reallymymail.com",
    "realtyalerts.ca",
    "recode.me",
    "recursor.net",
    "reliable-mail.com",
    "rhyta.com",
    "rmqkr.net",
    "royal.net",
    "rtrtr.com",
    "s0ny.net",
    "safe-mail.net",
    "safersignup.de",
    "safetymail.info",
    "safetypost.de",
    "sandelf.de",
    "saynotospams.com",
    "schafmail.de",
    "schrott-email.de",
    "secretemail.de",
    "secure-mail.biz",
    "secure-mail.cc",
    "selfdestructingmail.com",
    "sendspamhere.com",
    "shiftmail.com",
    "shitmail.me",
    "shitmail.org",
    "shitware.nl",
    "shmeriously.com",
    "shortmail.net",
    "sibmail.com",
    "sinnlos-mail.de",
    "slapsfromlastnight.com",
    "slaskpost.se",
    "smashmail.de",
    "smellfear.com",
    "snakemail.com",
    "sneakemail.com",
    "sneakmail.de",
    "snkmail.com",
    "sofimail.com",
    "sofort-mail.de",
    "sogetthis.com",
    "soodonims.com",
    "spam.la",
    "spam.su",
    "spam4.me",
    "spamail.de",
    "spamarrest.com",
    "spambob.com",
    "spambob.net",
    "spambob.org",
    "spambog.com",
    "spambog.de",
    "spambog.ru",
    "spambox.info",
    "spambox.irishspringrealty.com",
    "spambox.us",
    "spamcannon.com",
    "spamcannon.net",
    "spamcero.com",
    "spamcon.org",
    "spamcorptastic.com",
    "spamcowboy.com",
    "spamcowboy.net",
    "spamcowboy.org",
    "spamday.com",
    "spamex.com",
    "spamfree.eu",
    "spamfree24.com",
    "spamfree24.de",
    "spamfree24.eu",
    "spamfree24.info",
    "spamfree24.net",
    "spamfree24.org",
    "spamgoes.in",
    "spamgourmet.com",
    "spamgourmet.net",
    "spamgourmet.org",
    "spamherelots.com",
    "spamhereplease.com",
    "spamhole.com",
    "spamify.com",
    "spaminator.de",
    "spamkill.info",
    "spaml.com",
    "spaml.de",
    "spammotel.com",
    "spamobox.com",
    "spamoff.de",
    "spamslicer.com",
    "spamspot.com",
    "spamthis.co.uk",
    "spamthisplease.com",
    "spamtrail.com",
    "spamtroll.net",
    "speed.1s.fr",
    "spoofmail.de",
    "stuffmail.de",
    "super-auswahl.de",
    "supergreatmail.com",
    "supermailer.jp",
    "superrito.com",
    "superstachel.de",
    "suremail.info",
    "sweetxxx.de",
    "talkinator.com",
    "teewars.org",
    "teleworm.com",
    "teleworm.us",
    "temp-mail.com",
    "temp-mail.de",
    "temp-mail.org",
    "temp-mail.ru",
    "tempe-mail.com",
    "tempemail.biz",
    "tempemail.co.za",
    "tempemail.com",
    "tempemail.net",
    "tempinbox.co.uk",
    "tempinbox.com",
    "tempmail.eu",
    "tempmail.it",
    "tempmail2.com",
    "tempmaildemo.com",
    "tempmailer.com",
    "tempmailer.de",
    "tempomail.fr",
    "temporarily.de",
    "temporarioemail.com.br",
    "temporaryemail.net",
    "temporaryemail.us",
    "temporaryforwarding.com",
    "temporaryinbox.com",
    "temporarymailaddress.com",
    "tempthe.net",
    "thankyou2010.com",
    "thc.st",
    "thelimestones.com",
    "thisisnotmyrealemail.com",
    "thismail.net",
    "throwawayemailaddress.com",
    "tilien.com",
    "tittbit.in",
    "tizi.com",
    "tmailinator.com",
    "toomail.biz",
    "topranklist.de",
    "tradermail.info",
    "trash-amil.com",
    "trash-mail.at",
    "trash-mail.com",
    "trash-mail.de",
    "trash2009.com",
    "trash2010.com",
    "trash2011.com",
    "trashdevil.com",
    "trashdevil.de",
    "trashemail.de",
    "trashmail.at",
    "trashmail.com",
    "trashmail.de",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashmail.ws",
    "trashmailer.com",
    "trashymail.com",
    "trashymail.net",
    "trialmail.de",
    "trillianpro.com",
    "twinmail.de",
    "tyldd.com",
    "uggsrock.com",
    "umail.net",
    "uroid.com",
    "us.af",
    "venompen.com",
    "veryrealemail.com",
    "viditag.com",
    "viewcastmedia.com",
    "viewcastmedia.net",
    "viewcastmedia.org",
    "vomoto.com",
    "vpn.st",
    "vsimcard.com",
    "vubby.com",
    "wasteland.rfc822.org",
    "webemail.me",
    "weg-werf-email.de",
    "wegwerf-emails.de",
    "wegwerfadresse.de",
    "wegwerfemail.com",
    "wegwerfemail.de",
    "wegwerfmail.de",
    "wegwerfmail.info",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "wetrainbayarea.com",
    "wetrainbayarea.org",
    "wh4f.org",
    "whyspam.me",
    "willhackforfood.biz",
    "willselfdestruct.com",
    "winemaven.info",
    "wronghead.com",
    "wuzup.net",
    "wuzupmail.net",
    "www.e4ward.com",
    "www.mailinator.com",
    "wwwnew.eu",
    "x.ip6.li",
    "xagloo.com",
    "xemaps.com",
    "xents.com",
    "xmaily.com",
    "xoxy.net",
    "yapped.net",
    "yeah.net",
    "yep.it",
    "yogamaven.com",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "yourdomain.com",
    "yuurok.com",
    "zehnminuten.de",
    "zehnminutenmail.de",
    "zippymail.info",
    "zoaxe.com",
    "zoemail.com",
    "zomg.info"
];

/**
 * Check if an email address uses a disposable/temporary email domain
 * @param {string} email - Email address to check
 * @returns {boolean} - True if disposable, false otherwise
 */
export function isDisposableEmail(email) {
    if (!email || typeof email !== "string") {
        return false;
    }

    const emailLower = email.toLowerCase().trim();
    const domain = emailLower.split("@")[1];

    if (!domain) {
        return false;
    }

    return DISPOSABLE_EMAIL_DOMAINS.includes(domain);
}

/**
 * Validate email format using RFC 5322 compliant regex
 * @param {string} email - Email address to validate
 * @returns {boolean} - True if valid format, false otherwise
 */
export function isValidEmailFormat(email) {
    if (!email || typeof email !== "string") {
        return false;
    }

    // RFC 5322 compliant email regex (simplified but robust)
    const emailRegex = /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

    return emailRegex.test(email.trim());
}

/**
 * Get user-friendly validation message for email
 * @param {string} email - Email address to validate
 * @returns {object} - { valid: boolean, message: string }
 */
export function validateEmail(email) {
    // Check format first
    if (!isValidEmailFormat(email)) {
        return {
            valid: false,
            message: "Please enter a valid email address.",
        };
    }

    // Check for disposable domains
    if (isDisposableEmail(email)) {
        return {
            valid: false,
            message:
                "Please use a valid, permanent institutional or personal email address to complete registration.",
        };
    }

    return {
        valid: true,
        message: "Email is valid",
    };
}

/**
 * Get the domain from an email address
 * @param {string} email - Email address
 * @returns {string|null} - Domain or null if invalid
 */
export function getEmailDomain(email) {
    if (!email || typeof email !== "string") {
        return null;
    }

    const parts = email.toLowerCase().trim().split("@");
    return parts.length === 2 ? parts[1] : null;
}
